title: Doc Projet
description: Documentation du projet

# NE RIEN MODIFIER CI-DESSOUS SI VOUS N'ETES PAS CERTAINS DE CE QUE VOUS FAITES

# Thème
remote_theme: leskaribous/JustTheDocsTemplate

# Si vous utilisez GitHub Pages, assurez-vous que jekyll-remote-theme est inclus
plugins:
  - jekyll-remote-theme